### PR TITLE
About App Page Added

### PR DESCRIPTION
**Pull request by Bbiswabasu**
I have added just the basic part of About App page. #21

### CODE REVIEW

**Review by iamsh4shank — COMMENTED** [review]
Hey, can you add a screenshot :)

**Review by iamsh4shank — CHANGES_REQUESTED** [review]
Nice work @Bbiswabasu, Can you also add this as a description text in a text view which would be well formated - "Health Log is a smart and efficient android app provided to hospitals to maintain the logs of covid19 patients. They can store new patients and doctors and it will automatically assign the doctor to each patient. Doctors can also fill the recent logs of each patient in each visit which will update the family members by the patient’s report. "

And don't forget to squash the commits :)

**Comment by Bbiswabasu** [comment]
@robustTechie is this fine?

**Review by iamsh4shank — COMMENTED** [review]
Put everything in a center indentation and also squash the commits then I will merge this

**Comment by Bbiswabasu** [comment]
@robustTechie I have centre aligned the text and squashed all the commits

**Comment by iamsh4shank** [comment]
Merged, nice work @Bbiswabasu :)

**Pull request merged**
