### PR TITLE
Patient Delete Option added

### PR DESCRIPTION
**Pull request by Bbiswabasu**
# Related Issue
#7
 

# Prosposed Changes
- Added button to delete a patient

# Additional Info
- any additional information or context

# Checklist
- [ ] Tests
- [ ] Translations
- [ ] Documentations

# Screenshots

Original             |  Updated
:-------------------------:|:-------------------------:
Before deleting Patient P25_test_notification Screenshot_20201225-183717  |  After deleting Patient P25_test_notification Screenshot_20201225-183723

### CODE REVIEW

**Review by iamsh4shank — COMMENTED** [review]
Hey @Bbiswabasu nice work can you put one screen recording demonstrating the delete option :)

**Comment by Bbiswabasu** [comment]
https://user-images.githubusercontent.com/58428413/103150449-469a8700-479a-11eb-86c7-82bed1303d96.mp4

Deleting patient "P26_delete1"
@robustTechie is this fine?

**Comment by iamsh4shank** [comment]
Hey that's good, can you also add a confirmation dialog so that if the user clicked by mistake then it won't get deleted on just one click, you can take the logout button's confirmation for reference

**Comment by Bbiswabasu** [comment]
Initial state
Screenshot_20201228-192044

P63_test_delete patient selected to delete and confirmation dialog appears
Screenshot_20201228-192050

Patient successfully deleted
Screenshot_20201228-192056

@robustTechie is this fine now?

**Comment by iamsh4shank** [comment]
Yeah nice work

**Review by iamsh4shank — CHANGES_REQUESTED** [review]
Can you squash the commits :)

**Comment by Bbiswabasu** [comment]
@robustTechie done

**Comment by iamsh4shank** [comment]
Nice work :)

**Pull request merged**
