### PR TITLE
add switch day/night

### PR DESCRIPTION
**Pull request by spacemonkey1101**
# Related Issue
This is related to pull request #27 

# Prosposed Changes
added the switch in the settings page as advised. But there are some errors in the preferences of the settings due to which I was unable to build my code

### CODE REVIEW

**Review by iamsh4shank — COMMENTED** [review]
Hey @spacemonkey1101 can you tell what issue you faced?

**Comment by spacemonkey1101** [comment]
@robustTechie have a look at this
Kazam_screenshot_00068

**Comment by iamsh4shank** [comment]
Hey, @spacemonkey1101 is there any array file?

**Comment by spacemonkey1101** [comment]
no i cant find them in the repo

**Comment by iamsh4shank** [comment]
@spacemonkey1101 can you once pull the recent changes it is there in the app right now :) If you face any issue let me know

**Comment by spacemonkey1101** [comment]
ok

**Comment by spacemonkey1101** [comment]
@robustTechie 

some of it is solved

**Comment by iamsh4shank** [comment]
Can you send the whole log ?

**Comment by spacemonkey1101** [comment]
Kazam_screenshot_00046

**Comment by iamsh4shank** [comment]
Did you pull the current changes?

**Comment by spacemonkey1101** [comment]
@robustTechie  yes I did

**Comment by spacemonkey1101** [comment]
@robustTechie have you checked the issue?

**Comment by iamsh4shank** [comment]
can you send the current git log

**Pull request closed without merging**
