### PR TITLE
Added hospital profile page

### LINKED ISSUE #14: Hospital Profile page
We can also a hospital profile page in the app hospital tab were the name of the hospital, as well as a few other information like id, will be visible.

### PR DESCRIPTION
**Pull request by Droyder7**
# Related Issue
fixes #14  

Added hospital profile page in the app hospital tab where the name of the hospital, as well as a few other information like id, address, bed count & doctor count (optional) will be visible

# Screenshot

profile

### CODE REVIEW

**Review by iamsh4shank — COMMENTED** [review]
hey @Droyder7 can you squash the changes :)

**Comment by Droyder7** [comment]
@robustTechie I have removed unnecessary changes and force-pushed all commits in a single commit. Is this would be ok ?

**Comment by iamsh4shank** [comment]
Yeah Nice work @Droyder7

**Comment by iamsh4shank** [comment]
Merged :)

**Pull request merged**
