### PR TITLE
Added Issue Template, Pull Request template, Code Of Conduct and READMe enhancements

### PR DESCRIPTION
**Pull request by deytulsi18**
Pull Request with reference to #28

### CODE REVIEW

**Review by iamsh4shank — CHANGES_REQUESTED** [review]
Hey, @deytulsi18 can you squash the commits :)

**Comment by deytulsi18** [comment]
Actually you can do that as a maintainer in just one click.
Please squash and merge

[Google image](https://drive.google.com/file/d/1l8WeR18TebqXcXLODgPr8lgOIsf54UaA/view?usp=drivesdk)

**Comment by iamsh4shank** [comment]
Lol, I know that but the main purpose of the programs like this it to teach you people :)

**Comment by deytulsi18** [comment]
Oh! Ok I'll do that 
Did you mind anything btw?

**Comment by iamsh4shank** [comment]
No

**Pull request closed without merging**
